services:
# Authenticator
    auth_token_repository:
        class: Doctrine\ORM\EntityManager
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: ["AppBundle:AuthToken"]

    auth_token_authenticator:
        class: AppBundle\Security\AuthTokenAuthenticator
        arguments: ["@security.http_utils","@service_container"]
        public: false

# AuthToken for User
    auth_token_user_provider:
        class: AppBundle\Security\AuthTokenUserProvider
        arguments: ["@auth_token_repository", "@user_repository"]
        public: false

    user_repository:
        class: Doctrine\ORM\EntityManager
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: ["AppBundle:Client"]
